# Generated by Django 4.2.7 on 2024-01-30 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_reg', models.DateField(auto_now=True)),
                ('customer', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='username', to='myapp.client', verbose_name='Id клиента')),
                ('product', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='producttitle', to='myapp.products', verbose_name='Id товара')),
            ],
        ),
    ]
