# Generated by Django 4.2.7 on 2024-01-30 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='product_title', to='myapp.products', verbose_name='Id товара'),
        ),
    ]
